# Generated by Django 4.2.16 on 2024-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.AddField(
            model_name="user",
            name="education_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wechat_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="微信号码"
            ),
        ),
    ]
