# Generated by Django 4.2.16 on 2024-12-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_address_user_education_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wechat_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="微信号码"
            ),
        ),
    ]
