# Generated by Django 4.2.16 on 2024-12-03 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="模块名称")),
                ("description", models.TextField(verbose_name="模块描述")),
                ("disclaimer", models.TextField(verbose_name="模块声明")),
                ("need_times", models.IntegerField(default=5, verbose_name="标注次数")),
            ],
            options={
                "verbose_name": "标注模块",
                "verbose_name_plural": "标注模块",
                "db_table": "annotation_module",
            },
        ),
        migrations.CreateModel(
            name="ToxicLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="标签名称")),
            ],
            options={
                "verbose_name": "毒性标签",
                "verbose_name_plural": "毒性标签",
                "db_table": "toxic_label",
            },
        ),
        migrations.CreateModel(
            name="ToxicRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="风险等级",
                    ),
                ),
            ],
            options={
                "verbose_name": "毒性风险",
                "verbose_name_plural": "毒性风险",
                "db_table": "toxic_risk",
            },
        ),
        migrations.CreateModel(
            name="ToxicText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="文本内容")),
                ("times", models.IntegerField(default=0, verbose_name="标注次数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.annotationmodule",
                        verbose_name="标注模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "待标注文本",
                "verbose_name_plural": "待标注文本",
                "db_table": "toxic_text",
            },
        ),
        migrations.CreateModel(
            name="ToxicAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_toxic", models.BooleanField(verbose_name="是否有毒")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.toxictext",
                        verbose_name="标注文本",
                    ),
                ),
                (
                    "toxic_label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="annotation.toxiclabel",
                        verbose_name="毒性标签",
                    ),
                ),
                (
                    "toxic_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="annotation.toxicrisk",
                        verbose_name="毒性风险",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="标注用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "标注记录",
                "verbose_name_plural": "标注记录",
                "db_table": "toxic_annotation",
                "unique_together": {("text", "user")},
            },
        ),
    ]
